// Публичный вход в модуль core. Всё, что нужно снаружи, берётся отсюда.
export * from './types'
export { keyError } from './errors'
export { parseInput, parseLink, parseSubscriptionBody, parseSubscriptionUserinfo } from './keys/parseInput'
export { guessCountry, stripFlagEmoji, flagEmojiToCode } from './country'
export { normalizeRuleList } from './domains'
export type { NormalizedList } from './domains'
export { APP_PRESETS, GAMES_PRESET, expandProcessNames } from './presets'
export type { AppPreset } from './presets'
export { maskKey, redactConfig, redactLogLine } from './redact'
export { buildSingBoxConfig, buildProbeConfig, PRIVATE_NETS, PRIVATE_NETS_V4, PRIVATE_NETS_V6, PROXY_TAG, DIRECT_TAG, DEFAULT_DNS_REMOTE } from './config/build'
export type { BuildOptions, ProbeServer, RuleSetFile } from './config/build'
export { parseDnsSpec } from './config/dnsSpec'
export { toAsciiDomain } from './util/punycode'
export { default as RULESETS } from './rulesets.json'
